### ISSUE TITLE
GPG signing problems with bitcon-server

### ISSUE THREAD

**Issue by renich** [error10/bitcoin-dist#1]
Hey man,

Thanks for the repo and all. 

I changed my bitcoin.repo to be:

[bitcoin]
name=Bitcoin for Fedora - $basearch
baseurl=http://linux.ringingliberty.com/bitcoin/f$releasever/$basearch
failovermethod=priority
enabled=1
gpgcheck=1
# gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-bitcoin

gpgkey=http://linux.ringingliberty.com/bitcoin/RPM-GPG-KEY-bitcoin

[bitcoin-source]
name=Bitcoin for Fedora - $basearch - Source
baseurl=http://linux.ringingliberty.com/bitcoin/f$releasever/SRPMS
failovermethod=priority
enabled=0
# gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-bitcoin

gpgkey=http://linux.ringingliberty.com/bitcoin/RPM-GPG-KEY-bitcoin
gpgcheck=1

and I still get the following message:

warning: /var/cache/yum/x86_64/18/bitcoin/packages/bitcoin-server-0.7.2-2.fc18.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID 2d782480: NOKEY
Retrieving key from http://linux.ringingliberty.com/bitcoin/RPM-GPG-KEY-bitcoin

The GPG keys listed for the "Bitcoin for Fedora - x86_64" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.

 Failing package is: bitcoin-server-0.7.2-2.fc18.x86_64
 GPG Keys are configured as: http://linux.ringingliberty.com/bitcoin/RPM-GPG-KEY-bitcoin

You might just have forgotten to sign that package or... <gulp>

**Comment by error10** [comment]
These packages were inadvertently signed with the wrong key (I am currently managing multiple repos on the same build server and right now key management is a completely manual, offline process). New packages will be pushed shortly, signed with the correct key.

**Comment by renich** [comment]
On Mon, Jan 28, 2013 at 6:28 PM, error10 notifications@github.com wrote:

> These packages were inadvertently signed with the wrong key (I am
> currently managing multiple repos on the same build server and right now
> key management is a completely manual, offline process). New packages will
> be pushed shortly, signed with the correct key.

Still getting this:

Dependencies Resolved

# 

 Package                                                     Arch
                             Version

#          Repository                                    Size

Installing:
 bitcoin                                                     x86_64
                             0.7.2-2.fc18
        bitcoin                                      1.4 M
 bitcoin-server                                              x86_64
                             0.7.2-2.fc18
        bitcoin                                      721 k
Installing for dependencies:
 boost                                                       x86_64
                             1.50.0-4.fc18
         fedora                                        27 k
 libdb4-cxx                                                  x86_64
                             4.8.30-5.fc18
         fedora                                       610 k
 miniupnpc                                                   x86_64
                             1.6-7.fc18
        fedora                                        34 k
 openssl-compat-bitcoin                                      x86_64
                             1.0.0j-4ec.fc18
         bitcoin                                      1.3 M
 qrencode                                                    x86_64
                             3.3.1-4.fc18
        fedora                                        16 k

# Transaction Summary

Install  2 Packages (+5 Dependent packages)

Total size: 4.1 M
Installed size: 14 M
Downloading Packages:
warning:
/var/cache/yum/x86_64/18/bitcoin/packages/bitcoin-server-0.7.2-2.fc18.x86_64.rpm:
Header V4 RSA/SHA1 Signature, key ID 2d782480: NOKEY
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-bitcoin

The GPG keys listed for the "Bitcoin for Fedora - x86_64" repository are
already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.

 Failing package is: bitcoin-server-0.7.2-2.fc18.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-bitcoin

## 

It's hard to be free... but I love to struggle. Love isn't asked for; it's
just given. Respect isn't asked for; it's earned!
Renich Bon Ciric

http://www.woralelandia.com/
http://www.introbella.com/
