### ISSUE TITLE
problem upgrading to 090

### ISSUE THREAD

**Issue by jave** [error10/bitcoin-dist#11]
yum upgrade 
Loaded plugins: langpacks, refresh-packagekit, versionlock
Resolving Dependencies
--> Running transaction check
---> Package bitcoin-server.x86_64 0:0.8.6-3.fc20 will be updated
---> Package bitcoin-server.x86_64 0:0.9.0-2.fc20 will be an update
--> Processing Dependency: bitcoin-cli(x86-64) = 0.9.0 for package: bitcoin-server-0.9.0-2.fc20.x86_64
--> Processing Dependency: file:///usr/share/doc/selinux-policy/html/index.html for package: bitcoin-server-0.9.0-2.fc20.x86_64
--> Running transaction check
---> Package bitcoin-cli.x86_64 0:0.9.0-2.fc20 will be installed
---> Package bitcoin-server.x86_64 0:0.9.0-2.fc20 will be an update
--> Processing Dependency: file:///usr/share/doc/selinux-policy/html/index.html for package: bitcoin-server-0.9.0-2.fc20.x86_64
--> Finished Dependency Resolution
Error: Package: bitcoin-server-0.9.0-2.fc20.x86_64 (bitcoin)
           Requires: file:///usr/share/doc/selinux-policy/html/index.html
 You could try using --skip-broken to work around the problem

**Comment by losttime** [comment]
I'm having the same problem. Have already manually installed `selinux-policy-doc`

**Comment by error10** [comment]
Sorry, the bug from #9 slipped back in due to me working on the wrong (older) revision of the spec file when putting together 0.9.0. This will be fixed in 0.9.0-3 which is being built now and should be in the repo in a few hours.

**Comment by error10** [comment]
bitcoin-0.9.0-3 is now available and should resolve your issue. Please reply if you continue to have this problem.
