### ISSUE TITLE
Fedora released new miniupnpc, bitcoin is fixed to older version

### ISSUE THREAD

**Issue by hajosc** [error10/bitcoin-dist#12]
Error: Package: bitcoin-0.9.1-1.fc19.x86_64 (bitcoin)
           Requires: libminiupnpc.so.8()(64bit)
           Available: miniupnpc-1.6-9.fc19.x86_64 (fedora)
               libminiupnpc.so.8()(64bit)
           Installed: miniupnpc-1.9-1.fc19.x86_64 (@updates)
              ~libminiupnpc.so.10()(64bit)

Forcing a downgrade to older miniupnpc opens a can of worms for other dependencies :(

**Comment by error10** [comment]
Sorry, for some reason this was rebuilt for Fedora 20 but not Fedora 19. This has now been rebuilt and is available in the repos now.
