### ISSUE TITLE
Missing update of libboost in CentOS 6 packages

### ISSUE THREAD

**Issue by Kiwawa** [error10/bitcoin-dist#13]
It seems that the latest compilation of bitcoin now requires libboost 1.55:

Error: Package: bitcoin-server-0.9.3-2.el6.i686 (bitcoin)
           Requires: libboost_thread.so.1.55.0

But the distribution (example from http://linux.ringingliberty.com/bitcoin/el6/i386/repoview/ ) still contains 1.50 for all distributions [i386, x86_64, SRPMS]:

```
2013-03-24: boost-compat-bitcoin-1.50.0-5.1.el6
```

More people seems to have this same issue, here is one guy on stackoverflow:
http://stackoverflow.com/questions/27892940/updating-bitcoin-on-centos-jan-15

**Comment by error10** [comment]
This was an error on my part. I pushed the bitcoin update, but forgot to push the boost update it was built with.

This is now available in the repos; if you don't see it, run `yum clean metadata` and try again.

Sorry for the confusion.
