### ISSUE TITLE
Fedora 22 Alpha support

### ISSUE THREAD

**Issue by czaks** [error10/bitcoin-dist#15]
I am now using Fedora 22 alpha as my primary workstation OS. Unfortunately, you do not yet provide support for that release. I tried rebuilding the packages, but a linking time problem appears. I believe the bitcoin binary tried to link with the upstream openssl at compile time, so it can't link with the compat openssl, at runtime.

```
[chax@zbox tmp]$ rpm -q openssl-compat-bitcoin
openssl-compat-bitcoin-1.0.1k-1.fc22.x86_64
[chax@zbox tmp]$ rpm -q openssl
openssl-1.0.1k-2.fc22.x86_64
[chax@zbox tmp]$ rpm -q bitcoin
bitcoin-0.10.0-3.fc22.x86_64
[chax@zbox tmp]$ bitcoin-qt
bitcoin-qt: /opt/openssl-compat-bitcoin/lib/libcrypto.so.10: version `OPENSSL_1.0.1_EC' not found (required by bitcoin-qt)
[chax@zbox tmp]$ 
```

**Comment by czaks** [comment]
Ok, I removed the openssl-devel library and recompiled bitcoin with just openssl-compat-bitcoin-devel. It works now.

**Comment by error10** [comment]
Thanks.

I generally start building for new Fedora releases after they branch from rawhide. Since the last Bitcoin release was before the rawhide branch, I hadn't built it yet. The next release of Bitcoin will be built for F22.
