### ISSUE TITLE
bitcoin 0.11.0-3.fc22.x86_64 seems to be compiled with profiling

### ISSUE THREAD

**Issue by sciurius** [error10/bitcoin-dist#16]
$ rpm -qi bitcoin
Name        : bitcoin
Version     : 0.11.0
Release     : 3.fc22
Architecture: x86_64
Install Date: Wed 09 Sep 2015 17:23:32 CEST
Group       : Applications/System
Size        : 17055797
License     : MIT
Signature   : RSA/SHA256, Fri 28 Aug 2015 10:38:22 CEST, Key ID fc6e7e4ea436
Source RPM  : bitcoin-0.11.0-3.fc22.src.rpm
Build Date  : Fri 28 Aug 2015 03:23:14 CEST
Build Host  : koji.ringingliberty.com
Relocations : (not relocatable)
URL         : http://bitcoin.org/
Summary     : Peer-to-peer digital currency
Description :
Bitcoin is an experimental new digital currency that enables instant
...
$ strings /usr/bin/bitcoin-cli | grep builddir
/builddir/build/BUILD/bitcoin-0.11.0/src/bitcoin_cli-bitcoin-cli.gcda
/builddir/build/BUILD/bitcoin-0.11.0/src/libbitcoin_cli_a-rpcclient.gcda
/builddir/build/BUILD/bitcoin-0.11.0/src/libbitcoin_util_a-chainparamsbase.gcda
/builddir/build/BUILD/bitcoin-0.11.0/src/libbitcoin_util_a-clientversion.gcda
/builddir/build/BUILD/bitcoin-0.11.0/src/libbitcoin_util_a-rpcprotocol.gcda
/builddir/build/BUILD/bitcoin-0.11.0/src/libbitcoin_util_a-util.gcda
/builddir/build/BUILD/bitcoin-0.11.0/src/libbitcoin_util_a-utilstrencodings.gcda
/builddir/build/BUILD/bitcoin-0.11.0/src/libbitcoin_util_a-utiltime.gcda
/builddir/build/BUILD/bitcoin-0.11.0/src/compat/libbitcoin_util_a-glibc_compat.gcda
/builddir/build/BUILD/bitcoin-0.11.0/src/libbitcoin_util_a-random.gcda
/builddir/build/BUILD/bitcoin-0.11.0/src/support/libbitcoin_util_a-cleanse.gcda

**Comment by error10** [comment]
This should be resolved in 0.11.0-4.
