### ISSUE TITLE
CentOS 7.2 dependency issue with the Berkeley DB database library for C++

### ISSUE THREAD

**Issue by troelsarvin** [error10/bitcoin-dist#17]
Trying to install the "bitcoin" package on a CentOS 7 system:

```
# cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core)
```

Installing bitcoin-release-1-6.noarch.rpm went well, but then:

```
# yum install bitcoin
[...]
Error: Package: bitcoin-0.11.2-1.el7.x86_64 (bitcoin)
           Requires: libdb_cxx-4.8.so()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

Installing the libdb-cxx package doesn't work (it provides libdb_cxx-5.so -> libdb_cxx-5.3.so). Installing compat-db47 does not help either (it installs libdb_cxx-4.7.so).

**Comment by error10** [comment]
You need to install and enable the EPEL repository.

I'll make a change shortly to make the EPEL requirement explicit when installing the packages.

**Comment by troelsarvin** [comment]
Ah. Yes, that helped. Thanks.

**Comment by error10** [comment]
Fixed in bitcoin-release-2-1.noarch
