### ISSUE TITLE
Documentation: Can bitcoinxt directly replace bitcoin?

### ISSUE THREAD

**Issue by troelsarvin** [error10/bitcoin-dist#19]
For the FAQ, perhaps:
I'm currently running the bitcoin-server package. I know that bitcoin and bitcoinxt cannot be installed simultaneously. But can I remove the bitcoin package-set and use the bitcoinxt package-set instead without any further steps? Especially: Can the two package sets use the same database files, or does some kind of conversion need to happen?

**Comment by error10** [comment]
This is a good question. I've switched back and forth with no issues but I'll confirm with upstream about compatibility.

**Comment by troelsarvin** [comment]
It turns out that my question is answered in the "How do I switch to XT?" section at https://bitcoinxt.software/faq.html
I uninstalled the following packages: bitcoin bitcoin-utils bitcoin-server
and then installed the following packages: bitcoinxt bitcoinxt-utils bitcoinxt-server
and things work.
