### ISSUE TITLE
Dependency issue with RPM

### ISSUE THREAD

**Issue by rjosephwright** [error10/bitcoin-dist#2]
I installed bitcoin-release-1.4 on CentOS 6.3, then used yum to install bitcoin-server 0.8.1. After installing, bitcoind would not start but gave this error:

/usr/lib64/bitcoin/bitcoind: symbol lookup error: /usr/lib64/bitcoin/bitcoind: undefined symbol: EC_KEY_free

I learned (thanks to kind people on IRC) that there may be a need to also install an openssl-compat RPM, so I installed openssl-compat-bitcoin from the repo, which solved the problem. However, it seems that it should be included as a dependency so that yum installs it automatically.

**Comment by error10** [comment]
You're right, this should already be included as a dependency...Let's see what's going on.

**Comment by error10** [comment]
The bitcoin GUI package carried the correct dependencies, while the server package did not. This has been fixed. Updated packages will be made available within the next four hours.
