### ISSUE TITLE
profiling...Cannot open

### ISSUE THREAD

**Issue by troelsarvin** [error10/bitcoin-dist#20]
I've changed my bitcoin server from running bitcoin to bitcoinxt packages. Now, when I run bitcoin-cli commands, I get valid results, but also strange debug-like messages. Example:

[user@server ~]$ bitcoin-cli validateaddress 1GrrG8bC3vmqbyXaJQhkGqxr4zxxgVXfT6
{
    "isvalid" : false
}
profiling:/builddir/build/BUILD/bitcoinxt-0.11A/src/support/libbitcoin_util_a-cleanse.gcda:Cannot open
profiling:/builddir/build/BUILD/bitcoinxt-0.11A/src/libbitcoin_util_a-random.gcda:Cannot open
profiling:/builddir/build/BUILD/bitcoinxt-0.11A/src/compat/libbitcoin_util_a-glibc_compat.gcda:Cannot open
profiling:/builddir/build/BUILD/bitcoinxt-0.11A/src/libbitcoin_util_a-utiltime.gcda:Cannot open
profiling:/builddir/build/BUILD/bitcoinxt-0.11A/src/libbitcoin_util_a-utilstrencodings.gcda:Cannot open
profiling:/builddir/build/BUILD/bitcoinxt-0.11A/src/libbitcoin_util_a-util.gcda:Cannot open
profiling:/builddir/build/BUILD/bitcoinxt-0.11A/src/libbitcoin_util_a-rpcprotocol.gcda:Cannot open
profiling:/builddir/build/BUILD/bitcoinxt-0.11A/src/libbitcoin_util_a-clientversion.gcda:Cannot open
profiling:/builddir/build/BUILD/bitcoinxt-0.11A/src/libbitcoin_util_a-chainparamsbase.gcda:Cannot open
profiling:/builddir/build/BUILD/bitcoinxt-0.11A/src/libbitcoin_cli_a-rpcclient.gcda:Cannot open
profiling:/builddir/build/BUILD/bitcoinxt-0.11A/src/bitcoin_cli-bitcoin-cli.gcda:Cannot open

**Comment by error10** [comment]
You seem to be running an older release. Do you see this issue with the latest release?

**Comment by troelsarvin** [comment]
[user@server ~]$ rpm -qa 'bitcoin*'
bitcoin-release-2-1.noarch
bitcoinxt-0.11.0-3.el7.centos.x86_64
bitcoinxt-server-0.11.0-3.el7.centos.x86_64
bitcoinxt-utils-0.11.0-3.el7.centos.x86_64

**Comment by error10** [comment]
Update to the current release and try again.

**Comment by troelsarvin** [comment]
But I've run "yum clean all; yum update" several times. Maybe there's something about the versioning which makes yum think that bitcoinxt-server-0.11.0-3 is newer than bitcoinxt-server-0.11D-1?

**Comment by error10** [comment]
I've regenerated the repo; please `yum clean metadata` and try updating again.

**Comment by troelsarvin** [comment]
Unfortunately, it still doesn't work for me. I then downloaded the following files manually (and verified signatures):
bitcoinxt-0.11D-1.el7.x86_64.rpm
bitcoinxt-libs-0.11D-1.el7.x86_64.rpm
bitcoinxt-server-0.11D-1.el7.x86_64.rpm
bitcoinxt-utils-0.11D-1.el7.x86_64.rpm

Subsequently:
[root@server tmp]# yum localupdate bitcoinxt-*
Loaded plugins: fastestmirror
Examining bitcoinxt-0.11D-1.el7.x86_64.rpm: bitcoinxt-0.11D-1.el7.x86_64
bitcoinxt-0.11D-1.el7.x86_64.rpm: does not update installed package.
Examining bitcoinxt-libs-0.11D-1.el7.x86_64.rpm: bitcoinxt-libs-0.11D-1.el7.x86_64
Package bitcoinxt-libs not installed, cannot update it. Run yum install to install it instead.
Examining bitcoinxt-server-0.11D-1.el7.x86_64.rpm: bitcoinxt-server-0.11D-1.el7.x86_64
bitcoinxt-server-0.11D-1.el7.x86_64.rpm: does not update installed package.
Examining bitcoinxt-utils-0.11D-1.el7.x86_64.rpm: bitcoinxt-utils-0.11D-1.el7.x86_64
bitcoinxt-utils-0.11D-1.el7.x86_64.rpm: does not update installed package.
Nothing to do

**Comment by error10** [comment]
You should remove the existing packages and then reinstall them. I don't know what's going on with your copy of yum.
