### ISSUE TITLE
dnf install bitcoin fails

### ISSUE THREAD

**Issue by anomalyst** [error10/bitcoin-dist#21]
After:

`
sudo rpm -i bitcoin-release-2-1.noarch.rpm
sudo dnf install epel-release
sudo rpm -i epel-release-latest-7.noarch.rpm
sudo rpm -i bitcoin-release-2-1.noarch.rpm
sudo dnf install bitcoin
`

reports the following:

"Failed to synchronize cache for repo 'bitcoin' from 'https://linux.ringingliberty.com/bitcoin/el23/x86_64': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried, disabling."
I noticed the subdirectory path "el23/x86_64" does not exist.

It is followed by:
"Failed to open: /var/cache/dnf/epel-2b6dfc5904c26562/repodata/7c043ab5eefce471b825300b0d094c530618396868bddc2d94203300f7d5d8a9-updateinfo.xml.bz2."
Which I dont think is _your_ issue, but might be related, and I include it for completeness. If you can give me a clue as to the solution, I'd be grateful.

**Comment by error10** [comment]
You installed the wrong `bitcoin-release` RPM. Remove it and install the correct one.
