### ISSUE TITLE
Broken dependencies for bitcoinclassic-server

### ISSUE THREAD

**Issue by andrewbeard** [error10/bitcoin-dist#22]
The bitcoinclassic-server package seems to require bitcoin-utils and not bitcoinclassic-utils.  Trying to install on a CentOS 7 system results in the following:

> [root@bitcoin-node tmp]# yum install bitcoinclassic-server
> Loaded plugins: fastestmirror
> Loading mirror speeds from cached hostfile
> - base: mirror.vtti.vt.edu
> - epel: mirror.us.leaseweb.net
> - extras: mirror.umd.edu
> - updates: mirror.umd.edu
>   Resolving Dependencies
>   --> Running transaction check
>   ---> Package bitcoinclassic-server.x86_64 0:0.11.2.cl1-3.el7 will be installed
>   --> Processing Dependency: bitcoin-utils(x86-64) = 0.11.2.cl1 for package: bitcoinclassic-server-0.11.2.cl1-3.el7.x86_64
>   --> Finished Dependency Resolution
>   Error: Package: bitcoinclassic-server-0.11.2.cl1-3.el7.x86_64 (bitcoin)
>          Requires: bitcoin-utils(x86-64) = 0.11.2.cl1
>          Available: bitcoin-utils-0.10.0-1.el7.x86_64 (bitcoin)
>              bitcoin-utils(x86-64) = 0.10.0-1.el7
>          Available: bitcoin-utils-0.10.0-3.el7.x86_64 (bitcoin)
>              bitcoin-utils(x86-64) = 0.10.0-3.el7
>          Available: bitcoin-utils-0.10.1-1.el7.x86_64 (bitcoin)
>              bitcoin-utils(x86-64) = 0.10.1-1.el7
>          Available: bitcoin-utils-0.10.1-3.el7.x86_64 (bitcoin)
>              bitcoin-utils(x86-64) = 0.10.1-3.el7
>          Available: bitcoin-utils-0.10.2-1.el7.x86_64 (bitcoin)
>              bitcoin-utils(x86-64) = 0.10.2-1.el7
>          Available: bitcoin-utils-0.11.0-1.el7.x86_64 (bitcoin)
>              bitcoin-utils(x86-64) = 0.11.0-1.el7
>          Available: bitcoin-utils-0.11.0-3.el7.centos.x86_64 (bitcoin)
>              bitcoin-utils(x86-64) = 0.11.0-3.el7.centos
>          Available: bitcoin-utils-0.11.0-4.el7.centos.x86_64 (bitcoin)
>              bitcoin-utils(x86-64) = 0.11.0-4.el7.centos
>          Available: bitcoin-utils-0.11.1-1.el7.centos.x86_64 (bitcoin)
>              bitcoin-utils(x86-64) = 0.11.1-1.el7.centos
>          Available: bitcoin-utils-0.11.2-1.el7.x86_64 (bitcoin)
>              bitcoin-utils(x86-64) = 0.11.2-1.el7
>          Available: bitcoin-utils-0.11.2-2.el7.x86_64 (bitcoin)
>              bitcoin-utils(x86-64) = 0.11.2-2.el7
>   You could try using --skip-broken to work around the problem
>   You could try running: rpm -Va --nofiles --nodigest

**Comment by error10** [comment]
Well, that's embarrassing. I thought I'd gotten all of those.

New builds are in progress and should be up in a few hours.

**Comment by andrewbeard** [comment]
I just tried updating again with no luck.  Looking at the repo it seems like there haven't been any changes to the classic RPMs since the initial release on the 11th.  Should the repo be updated by now or is it still in progress?

**Comment by error10** [comment]
You're right. This really is not my weekend. The packages were built but not signed and pushed. I've signed and pushed them now and you should be able to update.

**Comment by andrewbeard** [comment]
Working now, thanks!
