### ISSUE TITLE
Bitcoin Classic is outdated

### ISSUE THREAD

**Issue by infertux** [error10/bitcoin-dist#25]
The RPM repo doesn't package the latest version available at https://bitcoinclassic.com/downloads/index.html

PS: Any plans to package [Bitcoin Unlimited](https://www.bitcoinunlimited.info/download) as well?

PPS: Thank you for your great work :)

**Comment by error10** [comment]
Bitcoin Classic 1.2.0 is not packaged because of several test failures in its test suite. I don't ship builds with failing tests, because this is people's money. At this time I cannot recommend using Bitcoin Classic.

I hadn't heard of Bitcoin Unlimited.

**Comment by infertux** [comment]
> Bitcoin Classic 1.2.0 is not packaged because of several test failures in its test suite. I don't ship builds with failing tests, because this is people's money. At this time I cannot recommend using Bitcoin Classic.

Oh that's interesting. I wasn't aware about that and would certainly agree that packaging software with a failing test suite is bad practice. However, I wasn't able to find any kind of automated builds online like Travis CI.

So I tried to run `./autogen.sh && ./configure --with-gui=no --disable-wallet --without-miniupnpc --disable-zmq && make check` on the `1.2` branch and it exited with zero/success. Could you point to the test failures you're referring to please?

![2017-01-18-225310_415x215_scrot](https://cloud.githubusercontent.com/assets/345702/22086520/f0303202-ddd0-11e6-8c3d-de6253546d2e.png)

> I hadn't heard of Bitcoin Unlimited.

From my limited understanding - any bystander here is very welcome to correct me - Bitcoin Unlimited has essentially become the same as Bitcoin Classic nowadays. The only main difference is that Unlimited is trying to keep their codebase close to Core by backporting new Core features whereas Classic codebase is going its own way and adding exclusive features such as "[FlexTrans](https://zander.github.io/posts/Flexible_Transactions/)". You can also check [this link](https://coin.dance/nodes#allNodes) for more details.

**Comment by error10** [comment]
The full test suite can be run with:

    qa/pull-tester/rpc-tests.py -extended

**Comment by zander** [comment]
Bitcoin Classic runs its unit tests before deployment successfully on
Ubuntu; https://launchpad.net/~bitcoinclassic/+archive/ubuntu/bitcoinclassic
log; https://launchpad.net/~bitcoinclassic/+archive/ubuntu/bitcoinclassic/+build/11820464/+files/buildlog_ubuntu-yakkety-amd64.bitcoinclassic_1.2.0-yakkety_BUILDING.txt.gz

Arch; https://aur.archlinux.org/packages/bitcoin-classic/
no logs, but available in your nearest VM.

The '-extended' tests are not typically run as they are not meant to be stable, are you running those?

**Comment by zander** [comment]
I forgot to ask, please show which unit tests are failing for you.

The [teamcity](https://zander.github.io/posts/ClassicQuality/#Continues_Integration_building) continues integration system runs all tests on all platforms (including several flavours of Linux) on a very regular basis. I don't use RPM based distro's, so maybe something is different there. 

I would like to hear what the test failure is that you hit. And please consider reporting them upstream next time you hit them.

**Comment by error10** [comment]
I've been running the -extended tests, the same as for building Bitcoin Core (where they virtually always pass). I'll build without running them this round, and give them another go in a week or two when I have some more time.

**Comment by infertux** [comment]
https://bitcoinclassic.com/news/closing.html
