### ISSUE TITLE
Fedora 26 packages depend on boost 1.60, which is unavailable

### ISSUE THREAD

**Issue by codewiz** [error10/bitcoin-dist#27]
I tried performing a system-upgrade from F25 to F26 today, and dnf fails like this:

Error: package bitcoin-core-0.14.1-1.fc25.x86_64 requires libboost_chrono.so.1.60.0()(64bit), but none of the providers can be installed.
package bitcoin-utils-0.14.1-1.fc25.x86_64 requires libboost_filesystem.so.1.60.0()(64bit), but none of the providers can be installed.

Looks like the Bitcoin packages for F26 built in January depend on a version of boost which has been dropped.

**Comment by error10** [comment]
Bitcoin has not yet been built for F26. Builds are now in progress.

**Comment by error10** [comment]
Bitcoin builds for F26 are now in the repo.
