### ISSUE TITLE
zmq

### ISSUE THREAD

**Issue by trocster** [error10/bitcoin-dist#28]
Hi, 

Are the srpms available ? 

Also can the binaries be compiled with zmq ?  https://github.com/bitcoin/bitcoin/blob/master/doc/zmq.md  (these are needed to get Lightning network support). 

Many thanks for the site and repo.

**Comment by error10** [comment]
Hi @trocster,

All SRPMS are on the web site. They are available going back to bitcoin 0.8.6 from 2012.

With regard to ZeroMQ support, this is currently enabled on Fedora. It is not yet enabled for RHEL/CentOS as these do not yet have Python 3 ZeroMQ bindings which Bitcoin requires to run ZeroMQ tests. When these bindings become available, ZeroMQ support will also be made available.

**Comment by trocster** [comment]
Many thanks for making the packages and for the info.
