### ISSUE TITLE
GPG signing issue

### ISSUE THREAD

**Issue by ewilded** [error10/bitcoin-dist#3]
Hey, thanks for the repo, I just conducted installation of the repo and the client from it, nevertheless I noticed some issue with GPG signature, not sure if I should worry about it:

Downloading Packages:
warning: rpmts_HdrFromFdno: Header V4 RSA/SHA1 Signature, key ID a4360c84: NOKEY
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-bitcoin
Importing GPG key 0xA4360C84:
 Userid : Bitcoin RPM Repository bitcoin@ringingliberty.com
 Package: bitcoin-release-1-4.noarch (installed)
 From   : /etc/pki/rpm-gpg/RPM-GPG-KEY-bitcoin

When I took a look at the key at  /etc/pki/rpm-gpg/RPM-GPG-KEY-bitcoin and compared it with the one from your website http://linux.ringingliberty.com/bitcoin/RPM-GPG-KEY-bitcoin
I noticed it differs with the last 4 characters. While the one from RPM ends with 'Gk8C', the one from the website ends with '8tg2'. I am a bit confused. Could you please verify this? I'll appreciate. Regards

**Comment by error10** [comment]
The key on the website is the same key; it carries an additional signature. This will be added into the next release of bitcoin-release RPM. I'll leave this issue open until this is done.

**Comment by error10** [comment]
This file has been updated in bitcoin-release-1-5.noarch.rpm released today. Please reopen if you find that this does not resolve your issue.
