### ISSUE TITLE
F20

### ISSUE THREAD

**Issue by Enelar** [error10/bitcoin-dist#6]
Could you please add fedora 20 support?

**Comment by error10** [comment]
Fedora 20 support will be added when the Fedora Project finalizes the repositories. Typically this happens just after the final Go/No-Go meeting. You should expect Bitcoin to be available on F20 within 0-7 days prior to the official release date.

**Comment by Enelar** [comment]
Thanks! Please make it as soon as possible. And wait for donation :)

https://blockchain.info/tx/09d3677e8a9fee1d930a8a56c33ac0e1f4b0369c7dfbc8c57607173cb9662d1f

**Comment by error10** [comment]
The next Go/No-Go meeting is tomorrow and you can be sure I will be watching closely. I also use Fedora :)

**Comment by Enelar** [comment]
FC20 is amazing, just instailed. Windows are compact, panel comfortable. Finaly brightness click away!

**Comment by Enelar** [comment]
So? You need help?

**Comment by error10** [comment]
Your question makes no sense?

**Comment by Enelar** [comment]
I mean: when F20 will be implemented?

**Comment by error10** [comment]
It was done already!

**Comment by Enelar** [comment]
Well, then update site, please: http://linux.ringingliberty.com/bitcoin/

**Comment by error10** [comment]
The site is up to date now.

**Comment by Enelar** [comment]
http://dagobah.net/flash/thank_you.swf
