### ISSUE TITLE
bitcoin-qt[10672]: segfault at 28 ip 00007f7e5d77f6a7 sp 00007fff140000c0 error 4 in libdb_cxx-4.7.so[7f7e5d642000+18c000]

### ISSUE THREAD

**Issue by a1exus** [error10/bitcoin-dist#7]
just installed

[root@XXXXXXXXXX ~]# tail -26 /var/log/yum.log 
Dec 13 13:43:42 Installed: bitcoin-release-1-5.noarch
Dec 13 15:57:31 Installed: boost-compat-bitcoin-system-1.50.0-5.1.el6.x86_64
Dec 13 15:57:32 Installed: boost-compat-bitcoin-chrono-1.50.0-5.1.el6.x86_64
Dec 13 15:57:32 Installed: boost-compat-bitcoin-thread-1.50.0-5.1.el6.x86_64
Dec 13 15:57:33 Installed: boost-compat-bitcoin-filesystem-1.50.0-5.1.el6.x86_64
Dec 13 15:57:34 Installed: qrencode-libs-3.4.2-1.el6.x86_64
Dec 13 15:57:35 Installed: boost-compat-bitcoin-date-time-1.50.0-5.1.el6.x86_64
Dec 13 15:57:36 Installed: boost-compat-bitcoin-program-options-1.50.0-5.1.el6.x86_64
Dec 13 15:57:37 Installed: boost-compat-bitcoin-regex-1.50.0-5.1.el6.x86_64
Dec 13 15:57:38 Installed: boost-compat-bitcoin-graph-1.50.0-5.1.el6.x86_64
Dec 13 15:57:39 Installed: boost-compat-bitcoin-wave-1.50.0-5.1.el6.x86_64
Dec 13 15:57:39 Installed: qrencode-3.4.2-1.el6.x86_64
Dec 13 15:57:40 Installed: boost-compat-bitcoin-locale-1.50.0-5.1.el6.x86_64
Dec 13 15:57:41 Installed: boost-compat-bitcoin-timer-1.50.0-5.1.el6.x86_64
Dec 13 15:57:42 Installed: boost-compat-bitcoin-math-1.50.0-5.1.el6.x86_64
Dec 13 15:57:43 Installed: boost-compat-bitcoin-signals-1.50.0-5.1.el6.x86_64
Dec 13 15:57:44 Installed: boost-compat-bitcoin-random-1.50.0-5.1.el6.x86_64
Dec 13 15:57:45 Installed: miniupnpc-1.6-6.el6.x86_64
Dec 13 15:57:46 Installed: boost-compat-bitcoin-python-1.50.0-5.1.el6.x86_64
Dec 13 15:57:47 Installed: openssl-compat-bitcoin-1.0.0k-1ec.el6.x86_64
Dec 13 15:57:48 Installed: boost-compat-bitcoin-serialization-1.50.0-5.1.el6.x86_64
Dec 13 15:57:49 Installed: db4-cxx-4.7.25-17.el6.x86_64
Dec 13 15:57:50 Installed: boost-compat-bitcoin-iostreams-1.50.0-5.1.el6.x86_64
Dec 13 15:57:51 Installed: boost-compat-bitcoin-test-1.50.0-5.1.el6.x86_64
Dec 13 15:57:52 Installed: boost-compat-bitcoin-1.50.0-5.1.el6.x86_64
Dec 13 15:57:53 Installed: bitcoin-0.8.6-1.el6.x86_64
[root@XXXXXXXXXX ~]# tail -1 /var/log/messages
Dec 13 15:58:08 XXXXXXXXXX kernel: bitcoin-qt[10672]: segfault at 28 ip 00007f7e5d77f6a7 sp 00007fff140000c0 error 4 in libdb_cxx-4.7.so[7f7e5d642000+18c000]
[root@XXXXXXXXXX ~]# cat /etc/redhat-release 
Scientific Linux release 6.4 (Carbon)
[root@XXXXXXXXXX ~]# uname -a
Linux XXXXXXXXXX 2.6.32-358.23.2.el6.x86_64 #1 SMP Wed Oct 16 11:13:47 CDT 2013 x86_64 x86_64 x86_64 GNU/Linux
[root@XXXXXXXXXX ~]#

**Comment by error10** [comment]
I can't really help you with filesystem corruption or defective hardware.

**Comment by a1exus** [comment]
I don't think there is a problem on my filesystem or hardware, but I can give it another shot on another system if you really think that's the problem, although other apps that I use works w/out any issues (I use this computer as my every day workstation, so if I had some issues I'd notice them as well in other apps, yet I don't see any issues at all on my end)

**Comment by error10** [comment]
If you can provide some more information then maybe there would be something to look at. But this is really non-specific.

**Comment by a1exus** [comment]
What kind of information are you looking for? I'd be happy to provide whatever you need)

**Comment by error10** [comment]
All of it.

I don't see this crash on CentOS 6.5, or on any other distribution, so it's highly likely that the problem is localized to your system. Bad hardware is most likely, especially if it doesn't _consistently_ crash.

**Comment by a1exus** [comment]
actually, I'm not sure what changed, I just tried running it again and it ran w/out any issues now) that's weird...

**Comment by error10** [comment]
Nothing changed, you just have defective hardware to find.

**Comment by a1exus** [comment]
I executed on same hardware though..
