### ISSUE TITLE
404 not found?

### ISSUE THREAD

**Issue by razrman** [error10/bitcoin-dist#8]
http://linux.ringingliberty.com/bitcoin/ellatest/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"

**Comment by razrman** [comment]
rpm -Uvh bitcoin-release-1-5.noarch.rpm
warning: bitcoin-release-1-5.noarch.rpm: Header V4 RSA/SHA1 Signature, key ID a4360c84: NOKEY
Preparing...                          ################################# [100%]
Updating / installing...
   1:bitcoin-release-1-5              ################################# [100%]

**Comment by error10** [comment]
Exactly what OS distribution are you using? Please provide any other relevant information; we should not have to ask for basic stuff like this!

**Comment by razrman** [comment]
Sorry the problem was with the amazon ami (/etc/system-release = Amazon Linux AMI release 2013.09), I edited the /etc/yum.repo.d/bitcoin.repo and hard coded el6. Then everything installed with the 'yum install bitcoin-server' The blockchain is loading now.

**Comment by error10** [comment]
Be careful. Amazon Linux is not supported and not recommended (for this or anything else). It's not a very stable distribution.
